version: "3.2"
services:
  web:
    image: ddliu/php-nginx
    container_name: arkphp-example-app-web
    restart: unless-stopped
    volumes:
      - ./app:/app:ro
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./data:/data
    working_dir: /app
    ports:
      - 8090:80
  cli:
    image: ddliu/php-nginx
    container_name: arkphp-example-app-cli
    restart: unless-stopped
    volumes:
      - ./app:/app:ro
      - ./config/cron.conf:/var/spool/cron/crontabs/root
      - ./config/supervisor.conf:/etc/supervisor/conf.d/app.conf
      - ./data:/data
    working_dir: /app